### ISSUE TITLE
Subset operator works with geographic coordinates while S2 datasets are opened in UTM projection

### ISSUE THREAD

**Issue by radosuav** [DHI-GRAS/processing_gpf#10]
When S2 dataset is opened in QGIS using GDAL 2.1 it is displayed in the native UTM projection. If the user then tries to create a spatial subset using the SNAP subset operator and selects "Canvas extent" or "Select extent on canvas" options, the subset extent will also be specified in the UTM projection. However, SNAP Subset operator expects the extent in geographic (lat/long) coordinates and so the subset operation will fail.

I see three possible solutions:
1. Inform the user about the issue and instruct to turn On The Fly (OTF) reprojection on with EPSG:4326 reference system.
2. Detect when canvas-selected extent is begin used and the canvas projection is in UTM and automatically convert the extent to EPSG:4326 coordinates.
3. Detect when canvas-selected extent is begin used and the canvas projection is in UTM and convert the extent to pixel coordinates and use the "region" Subset parameter instead of "geoRegion". See SNAP help for Subset operator for more details.

**Comment by j08lue** [comment]
At first sight, I like solution 3 best. Then the subset comes out in the same projection as the input.

**Comment by radosuav** [comment]
Fixed in https://github.com/DHI-GRAS/qgis-processing-gpf/commit/646d406229fc917f30b19a75541f85d76686a7bd using automatic reprojection functionality available in QGIS 3.
