### ISSUE TITLE
BEAM tools cannot be chained together in QGIS models

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/processing_gpf#23]
> It is not possible to build a model using BEAM tools. I tried to build a model using BEAM tools. The model would process the following consecutive steps starting with a MERIS RR product in N1 format: “CoastColour Pre-Processing and Pixel Classification” -> “MERIS MPH Processor”. The problem occurs after the first step, the MPH Processor is not able to work with the output of the Pixel Classification. I tried to save the outputs of both steps and realized that the only saving option is to use GeoTiff. Unfortunately the BEAM tools need DIMAP as input to work properly. Now I guess that the model uses geotiff as temporary format if you just connect the two processes and therefore the second process fails.

**Comment by j08lue** [comment]
This is a known limitation of BEAM. And even if you change the output file extension of the first processing step to .dim manually, it will fail because the model driver tries to perform checks on the intermediate product using GDAL that fail on .dim files.

So there is unfortunately no solution to this and we must ask you to use a workflow instead of a model. One could also chain the commands into a BEAM graph and integrate that with QGIS, but this is a bit cumbersome

**Comment by radosuav** [comment]
There is currently no plan to add any new functionality to BEAM provider (e.g. the ability to build BEAM graphs). Only SNAP provider will be developed further.
