### ISSUE TITLE
Band Maths Algorithm in Models

### ISSUE THREAD

**Issue by PedroVenancio** [DHI-GRAS/processing_gpf#26]
Band Maths Algorithm works well when used by itself, but when integrated in models, it gives an error and doesn't work:

> Algorithm Teste BandMath starting...
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Loading external tools... 
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/s1tbx 
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/rstb 
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/probavbox 
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/s2tbx 
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/s3tbx 
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/smos 
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/java 
> SEVERE: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Failed scan for Tools descriptors: I/O problem: /home/pedro/snap/java 
> java.lang.IllegalArgumentException: code is null 
> at org.esa.snap.core.jexp.impl.ParserImpl.parse(ParserImpl.java:129) 
> at org.esa.snap.core.jexp.impl.ParserImpl.parse(ParserImpl.java:115) 
> at org.esa.snap.core.gpf.common.BandMathsOp.createTerm(BandMathsOp.java:447) 
> at org.esa.snap.core.gpf.common.BandMathsOp.initialize(BandMathsOp.java:267) 
> at org.esa.snap.core.gpf.internal.OperatorContext.initializeOperator(OperatorContext.java:486) 
> at org.esa.snap.core.gpf.internal.OperatorContext.getTargetProduct(OperatorContext.java:273) 
> at org.esa.snap.core.gpf.Operator.getTargetProduct(Operator.java:387) 
> at org.esa.snap.core.gpf.graph.NodeContext.initTargetProduct(NodeContext.java:77) 
> at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:195) 
> at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:178) 
> at org.esa.snap.core.gpf.graph.GraphContext.initOutput(GraphContext.java:162) 
> at org.esa.snap.core.gpf.graph.GraphContext.(GraphContext.java:91) 
> at org.esa.snap.core.gpf.graph.GraphContext.(GraphContext.java:64) 
> at org.esa.snap.core.gpf.graph.GraphProcessor.executeGraph(GraphProcessor.java:130) 
> at org.esa.snap.core.gpf.main.DefaultCommandLineContext.executeGraph(DefaultCommandLineContext.java:84) 
> at org.esa.snap.core.gpf.main.CommandLineTool.executeGraph(CommandLineTool.java:498) 
> at org.esa.snap.core.gpf.main.CommandLineTool.runGraph(CommandLineTool.java:346) 
> at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:245) 
> at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:146) 
> at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:118) 
> at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54) 
> at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34) 
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
> at java.lang.reflect.Method.invoke(Method.java:498) 
> at org.esa.snap.runtime.Launcher.lambda$run$0(Launcher.java:55) 
> at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189) 
> at org.esa.snap.runtime.Launcher.run(Launcher.java:51) 
> at org.esa.snap.runtime.Launcher.main(Launcher.java:31) 
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
> at java.lang.reflect.Method.invoke(Method.java:498) 
> at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62) 
> at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57) 
> 
> Error: code is null

Besides that, saving the model stores the Band Maths parameters values in the xml file. But, when editing the model in Processing, the Band Maths parameters values always return to default values (expression: empty; name of the output band: result; data type: float32; no data value: NaN).

As a feature request for Band Maths, it would be good to reference the input product/raster bands as some alias (for exemple b1, b2, ..., bn; or a, b, c, d, ..., like in SAGA Raster Calculator), because at this time it's necessary to know the bands name, witch limits its use in a generic model.

**Comment by radosuav** [comment]
@PedroVenancio could you test the fix from #29.

Regarding the referencing of raster bands, I think the optimal solution would be to add support for ParameterBands (and other parameters from GPFParameters) to GPFModelerDialog. That way the user could get a list of band names with a button click and select the ones which are needed in the band math expression (similarly to what is possible with stand alone band math operator). However this might require a bit of work so I'm not sure when it might be implemented.

**Comment by PedroVenancio** [comment]
Fix confirmed @radosuav !

Thank you very much!!
