### ISSUE TITLE
problem with BEAM/SNAP reprojection

### ISSUE THREAD

**Issue by ctottrup** [DHI-GRAS/processing_gpf#3]
When trying to reproject using BEAM and/or SNAP reproject the execution stops with folllowing message: "coercing to Unicode: need string or buffer, NoneType found"

**Comment by radosuav** [comment]
This should already be fixed in the GitHub code (in e1b6e58bc217bca9462187eb83d441a7b9e6caf7). However, there is another (similar) issue affecting the reproject algorithm which should be fixed with PR #4.

**Comment by ctottrup** [comment]
thx, it works now :-)
