### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by PedroVenancio** [DHI-GRAS/processing_gpf#32]
Sometimes, when I run processes / graphs for large areas, I get a GC overhead limit exceeded, and the process crashes:

Error: GC overhead limit exceeded 
-- org.jblas INFO Deleting /tmp/jblas6449420543174661684/libjblas.so 
-- org.jblas INFO Deleting /tmp/jblas6449420543174661684/libjblas_arch_flavor.so 
-- org.jblas INFO Deleting /tmp/jblas6449420543174661684 

Maybe I should select smaller areas or divide the operations by several graphs, but the strange thing is that I've 16GB of RAM, and the java process started by Processing GPF never go above 4.2GB. Instead, the java process started by SNAP Desktop, easily eats 10GB of RAM, without crash.

I already adjusted the maximum memory usage to 14GB in gpt.vmoptions file (-Xmx14336m), but the same happens.

Is there any memory limit imposed by GPF, Processing or QGIS itself?

**Comment by radosuav** [comment]
As far as I know there should be no memory limit imposed by Processing_GPF, Processing or QGIS because all Processing_GPF does is constructs a GPF file and invokes gpt.exe. 

In the QGIS Log Message Panel under the Processing tab you can find the gpt.exe call constructed by Processing_GPF. On Windows it should be something like: "C:\Program Files\snap\bin\gpt.exe" "c:\users\user_name\appdata\local\temp\gpf.xml" -e -q 4. You can copy this call and run it directly from command prompt to double check that you run into the same memory limitations. If that is the case then I would recommend to report the issue on the SNAP forum (http://forum.step.esa.int/).

**Comment by PedroVenancio** [comment]
Hi @radosuav ,

I think I've found the problem.

I'm using Processing_GPF on Linux, and so I've tried to run the graph on terminal with something like

`"/home/pedro/snap/bin/gpt.sh" "/home/pedro/SIG/gpf.xml" -e -q 4`

and I faced again with the GC overhead crash, at 4.2GB of RAM.

So, I remembered that when I've installed Processing_GPF for the first time, I had to change the gpt file name in ../snap/bin/ to gpt.sh, because the Processing_GPF call uses the extension. Indeed, this has worked, but somehow, using ../snap/bin/gpt.sh it ignores the java parameters defined in gpt.vmoptions, and uses a standard maximum memory of about 4.2GB, witch lead to the GC overhead.

In that way, after I put -Xmx11G in gpt.vmoptions, and run the command like 

`"/home/pedro/snap/bin/gpt" "/home/pedro/SIG/gpf.xml" -e -q 4`

even using a very large geographical area, with peaks of 11.4GB of memory used, the process come to the end, with the expected result.

So, I think the solution is simply change the GPFUtils.py file 

from

```
elif key == GPFUtils.snapKey():
	# check if running on windows or other OS
	if platform.system() == "Windows":
		batchFile = os.path.join("bin", "gpt.exe")
	else:
		batchFile = os.path.join("bin", "gpt.sh")
	try:
		threads = int(float(ProcessingConfig.getSetting(GPFUtils.S1TBX_THREADS)))
	except:
		threads = 4
```

to 

```
elif key == GPFUtils.snapKey():
	# check if running on windows or other OS
	if platform.system() == "Windows":
		batchFile = os.path.join("bin", "gpt.exe")
	else:
		batchFile = os.path.join("bin", "gpt")
	try:
		threads = int(float(ProcessingConfig.getSetting(GPFUtils.S1TBX_THREADS)))
	except:
		threads = 4
```

I dont know if it is the same with Beam, because it was discontinued, and I suspect that in early times of SNAP, the gpt.sh was used as default [0], but it seems that it is not anymore.

I can not test on MacOS, but trusting in this discussion [0], it also worked with gpt.

Should I make a PR with that small change?

Thank you very much!

[0] http://forum.step.esa.int/t/gpt-command-line-in-ubuntu/292/3

**Comment by radosuav** [comment]
Thanks a lot for further investigation and finding the solution! I will make a fix for it tomorrow because I just noticed other small things that need updating in GPFUtils.
