### ISSUE TITLE
SNAP 5 breaks algorithms on multi-resolution products

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/processing_gpf#37]
from @ctottrup:

> I am a struggling a bit to handle the new S2 format in QGIS and also noticed some changes in SNAP which I believe compromise the interface with QGIS. 
> In SNAP you now open the S2 file by selecting the xml file – and all bands (irrespective of resolution) are being opened, but in previous versions I seem to recall you were asked to select whether you will be opening 10, 20 or 60 m resolution data. I can see problems with the new reader in terms of opening data in QGIS as the latter requires data to be in similar resolution – is this being handled and in positive case how? I have tried to update to latest processing but when using SNAP algorithms such as read and subset I still get an error saying that multi-size raster’s cannot be handled?

**Comment by j08lue** [comment]
from @radosuav:

> The new opening mechanism of S2 images is a "feature" of SNAP 5.0 and it's not related to any changes made in the Processing_GPF plugin or QGIS. However, it exposes a bug because many SNAP operators cannot handle multi-size product. If you open a S2 scene in SNAP 5 and try to do subset operation (or other operation which assumes that all bands have the same resolution) it will give you a similar warning message and a link to https://senbox.atlassian.net/browse/SNAP-1. The way to resolve the problem is to first run Resampling operator (which I have added to Processing_GPF when updating to support SNAP 5) and then subset. In practice this means that most GPF graphs that deal with S2 will need to have Resampling operator as the first algorithm. This is also the case with S2 images in the old format (which can be opened in QGIS) because even though only one resolution is opened in QGIS, a multi-resolution image must be passed to SNAP from processing (see https://github.com/DHI-GRAS/processing_gpf/commit/4ce52e728d11c9b0c61aaf0c3cf0be9b546e1050). This is a big pain because resampling takes a long time. In the future (hopefully in SNAP 6 but I don't know) all the operators should be able to handle multi-size products. 
> 
> Support of the new S2 format has been added to GDAL and will be included in GDAL 2.1.3 which is basically ready but not released yet (see https://trac.osgeo.org/gdal/wiki/Release/2.1.3-News). When the next minor releases of QGIS are out in exactly 30 days they should be compiled against the new GDAL version and support opening the new S2 SAFE files directly in QGIS. Until that time you have to first process the S2 file in SNAP (e.g. through Processing GPF) and then the output can be visualised in QGIS. But this again means resampling which is very slow...

**Comment by j08lue** [comment]
from @radosuav:

> Today version 5.0.1 of SNAP came out but it seems to have issues with the Resampling operator (https://github.com/senbox-org/snap-engine/issues/75). 
> 
> Also there appears to be an issue with GeoTIFF-BigTIFF writer when it has to save metadata (https://github.com/senbox-org/snap-engine/issues/76). An easy temporary fix would be to change the default format to GeoTIFF in GPFAlgorithm.py (https://github.com/DHI-GRAS/processing_gpf/blob/GW-A_dev/GPFAlgorithm.py#L305) but that would mean that rasters bigger then 4 GB cannot be processed. What do you think?

**Comment by j08lue** [comment]
@radosuav We could also just skip support for SNAP 5.0.1 for now and wait for https://github.com/senbox-org/snap-engine/issues/75 to be resolved.

**Comment by radosuav** [comment]
Yes, I think that we should stick to SNAP 5.0.0 for now. 

Could you test the performance of the attached resampling-subsetting model (you need to change the extension to .xml) on an S2 scene with SNAP 5.0.0. In my case it seemed quite slow even with small subsets but I'm not sure if that is a local issue.
[subset_60.txt](https://github.com/DHI-GRAS/processing_gpf/files/734674/subset_60.txt)

**Comment by ctottrup** [comment]
Just tested resampling-subsetting - took 5 minutes for AOI of 50x85 km. Two questions: [1] seems you are required to provide an extent - how to force processing of full extent?  [2] Only one band in output, how to output all spectral bands?

**Comment by radosuav** [comment]
That was just a model for quick testing/benchmarking which is why it asks for extent and subsets to only one band. 

To resample the whole scene and all bands just use the Resampling operator by itself (i.e. no model is required). To subset either by extent or bands after resampling use [this model](https://github.com/DHI-GRAS/processing_gpf/files/734992/resample_subset.txt) . But in that case the canvas projection must be set to geographic and extent selected on canvas because of #10.

**Comment by radosuav** [comment]
A temporary workaround for the resampling issue in SNAP 5.0.1 is to create a graph: Read > Resampling > Subset > Resampling > Write

Taken from http://forum.step.esa.int/t/resampling-and-subsetting-s2-scene-and-saving-as-geotiff-bigtiff-does-not-work/4588/2.

I would still stick to SNAP 5.0.0 for now in WOIS.

**Comment by j08lue** [comment]
Is SNAP 5.0.1 even officially released yet?
![image](https://cloud.githubusercontent.com/assets/3404817/22784735/8b5b0b4c-eed1-11e6-8a98-d8867ee5d19a.png)
http://step.esa.int/main/download/

**Comment by radosuav** [comment]
The minor updates are available from within SNAP from Tools > Plugins > Check for Updates or by clicking update message popping up in the lower right corner.

**Comment by radosuav** [comment]
We are now using SNAP 7, where this should work.
