### ISSUE TITLE
New version of the plugin

### ISSUE THREAD

**Issue by PedroVenancio** [DHI-GRAS/processing_gpf#38]
I think the last fixes are relevant enough for a new version of the plugin (1.4.2 or 1.5.0).

What do you think?

Thanks! Best regards!

**Comment by radosuav** [comment]
I agree :) Just wanted to wait a couple of days to make sure that nothing new comes up. But I will prepare a release early next week.

**Comment by radosuav** [comment]
Done in aed27ba9923dbd75e00f45b3b528485630c5fc2d and http://plugins.qgis.org/plugins/processing_gpf/version/1.4.2/.

**Comment by PedroVenancio** [comment]
Thank you very much @radosuav !
I've posted an article about the use of the plugin, in the portuguese QGIS user group. Unfortunately, it is in portuguese, but Google translator help somehow:
https://translate.google.pt/translate?sl=pt&tl=en&js=y&prev=_t&hl=pt-PT&ie=UTF-8&u=http%3A%2F%2Fqgis.pt%2Fblog%2F2017%2F02%2F02%2Fprocessamento-de-dados-de-radar-sentinel-1-com-o-qgis%2F&edit-text=&act=url
