### ISSUE TITLE
How to add new SNAP processes?

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/processing_gpf#41]
Not all SNAP processes are available in `processing_gpf`. How can a user add these? 

For example `Radar > Interferometric` processes.

**Comment by j08lue** [comment]
If it is only a **single algorithm** that should be made available, it suffices to add a description file to the respective folder, e.g. [s1tbx_description](https://github.com/DHI-GRAS/processing_gpf/tree/GW-A_dev/s1tbx_description).

You can get the exact names of the parameters from the process you want to add, where you click on `File > Display Parameters`:

![image](https://cloud.githubusercontent.com/assets/3404817/25804214/dc12c5f2-33fa-11e7-8df7-5d688dbad16f.png)

![image](https://cloud.githubusercontent.com/assets/3404817/25804221/ea751f82-33fa-11e7-84ed-5ad3d381c492.png)

If you want to add a **chain** of algorithms, you can build it with the GPF Graph Builder as described in the [README](https://github.com/DHI-GRAS/processing_gpf/blob/GW-A_dev/README.md).

**Comment by j08lue** [comment]
We welcome your added algorithm interfaces as contributions.

**Comment by radosuav** [comment]
Some more info: the algorithm description files are based on GRASS description files. So the syntax for setting processing parameters should be as described [here](https://github.com/DHI-GRAS/ESA_Processing/blob/master/algs/grass7/grass7.txt) (note that this document is not complete).

**Comment by ewamiti** [comment]
Hi j08lue
I don't follow this on how to add a new process from SNAP to QGIS-WOIS. Could you guide me with one illustrative example.

thank you

**Comment by j08lue** [comment]
@ewamiti something along these lines:
```
Interferogram-Formation
s1tbx_Interferogram-Formation
Interferogram Formation
Radar
ParameterRaster|sourceProduct|Input image|False|False
ParameterBoolean|subtractFlatEarthPhase|Subtract Flat Earth phase|True
ParameterNumber|srpPolynomialDegree|Degree of Flat Earth polynomial|None|None|5
ParameterNumber|srpNumberPoints|Number of Flat Earth points|1|None|501
ParameterNumber|orbitDegree|Orbit interpolation degree|None|None|3
ParameterBoolean|includeCoherence|Include coherence estimation|True
ParameterBoolean|squarePixel|Square Pixel|True
ParameterNumber|cohWinRg|Coherence Range Window Size|None|None|10
ParameterNumber|cohWinAz|Coherence Azimuth Window Size|None|None|10
OutputRaster|-out|Output Image
```
So the first lines are some metadata and the rest specifies the parameters following the format mentioned [above](https://github.com/DHI-GRAS/processing_gpf/issues/41#issuecomment-299868190).

You can also look at the other [existing description files](https://github.com/DHI-GRAS/processing_gpf/blob/GW-A_dev/s1tbx_description) for comparison.

**Comment by ewamiti** [comment]
@j08lue 
At what point on QGIS do i add these line to be able to have the process in WOIS. I think this is my main problem for now

**Comment by j08lue** [comment]
You make a text file called `Interferogram-Formation.txt` with the above lines in it and place it in this folder: `C:\Users\YOUR_USERNAME\.qgis2\python\plugins\processing_gpf\s1tbx_description`.

When you restart QGIS, you will have the new **Interferogram Formation** algorithm:

![image](https://cloud.githubusercontent.com/assets/3404817/25887762/af3ed542-3563-11e7-8972-9b5dc8938cbc.png)

NB: I did not test the algorithm implementation yet. If you do, please let me know whether it works.

**Comment by ewamiti** [comment]
Thanks a lot. Done with this now. But another question.
Where do you get these lines? when i open the **interferogram parameters** as you illustrated above https://github.com/DHI-GRAS/processing_gpf/issues/41#issuecomment-299868190, they look different.

**Comment by j08lue** [comment]
Different from my screenshot? Please show. What version of SNAP are you using? This is `5.0.4`.

Translating the parameters that you see in SNAP (as in my screenshot) to the GRASS style description file (as the lines above) requires a bit of trial-and-error and learning from examples.

**Comment by ewamiti** [comment]
From 
**<parameters>
    <subtractFlatEarthPhase>true</subtractFlatEarthPhase>
    <srpPolynomialDegree>5</srpPolynomialDegree>
    <srpNumberPoints>501</srpNumberPoints>
    <orbitDegree>3</orbitDegree>
    <includeCoherence>true</includeCoherence>
    <cohWinAz>10</cohWinAz>
    <cohWinRg>10</cohWinRg>
    <squarePixel>true</squarePixel>
</parameters>**

to 

**Interferogram
s1tbx_InterferogramFormation
Interferogram Formation
Radar
ParameterRaster|sourceProduct|Input image|False|False
ParameterBoolean|subtractFlatEarthPhase|Subtract Flat Earth phase|True
ParameterNumber|srpPolynomialDegree|Degree of Flat Earth polynomial|None|None|5
ParameterNumber|srpNumberPoints|Number of Flat Earth points|1|None|501
ParameterNumber|orbitDegree|Orbit interpolation degree|None|None|3
ParameterBoolean|includeCoherence|Include coherence estimation|True
ParameterBoolean|squarePixel|Square Pixel|True
ParameterNumber|cohWinRg|Coherence Range Window Size|None|None|10
ParameterNumber|cohWinAz|Coherence Azimuth Window Size|None|None|10
OutputRaster|-out|Output Image**

**Comment by ewamiti** [comment]
From this

<parameters>
    <subtractFlatEarthPhase>true</subtractFlatEarthPhase>
    <srpPolynomialDegree>5</srpPolynomialDegree>
    <srpNumberPoints>501</srpNumberPoints>
    <orbitDegree>3</orbitDegree>
    <includeCoherence>true</includeCoherence>
    <cohWinAz>10</cohWinAz>
    <cohWinRg>10</cohWinRg>
    <squarePixel>true</squarePixel>
</parameters>


to this 

Interferogram
s1tbx_InterferogramFormation
Interferogram Formation
Radar
ParameterRaster|sourceProduct|Input image|False|False
ParameterBoolean|subtractFlatEarthPhase|Subtract Flat Earth phase|True
ParameterNumber|srpPolynomialDegree|Degree of Flat Earth polynomial|None|None|5
ParameterNumber|srpNumberPoints|Number of Flat Earth points|1|None|501
ParameterNumber|orbitDegree|Orbit interpolation degree|None|None|3
ParameterBoolean|includeCoherence|Include coherence estimation|True
ParameterBoolean|squarePixel|Square Pixel|True
ParameterNumber|cohWinRg|Coherence Range Window Size|None|None|10
ParameterNumber|cohWinAz|Coherence Azimuth Window Size|None|None|10
OutputRaster|-out|Output Image

**Comment by ewamiti** [comment]
sorry 
what i mean is translating from the parameters displayed on SNAP to the Grass style.

Is there a way i can learn this fast?

**Comment by j08lue** [comment]
I guess the only way is to look at existing implementations of algorithms and compare what you see in the description files with SNAPs XML parameter lists.

As for the different parameter types and their configuration, you can look at the [`parameters.py`](https://github.com/qgis/QGIS/blob/master/python/plugins/processing/core/parameters.py) file from QGIS. A line like [this one](https://github.com/qgis/QGIS/blob/49c688bbe4c4537b0f9ce2b2b01854cddd600d12/python/plugins/processing/core/parameters.py#L212) tells you that the fields of `ParameterBoolean` are `name='', description='', default=None, optional=False`.

So a line like `ParameterBoolean|subtractFlatEarthPhase|Subtract Flat Earth phase|True` defines a `ParameterBoolean` type parameter with `name='subtractFlatEarthPhase'`, `description='Subtract Flat Earth phase'`, `default=True` and `optional=False` (omitted).

The only things you explicitly get from the SNAP XML parameter list is the `name` and the `default` value. You have to get the `description` from the GUI text and guess the parameter type (`true/false` will always be `ParameterBoolean`).

Good luck. :-)

If this turns out too difficult, please open a new issue with the algorithms you would like to add and we can perhaps add them for you at some point.

**Comment by ewamiti** [comment]
Created issue #42
Eric Kenya Water Institute (KEWI)
+254722477771, Skype: ewamiti
wamiti@kewi. or.ke
CallSend SMSAdd to SkypeYou'll need Skype CreditFree via Skype 

    On Tuesday, May 9, 2017 5:59 PM, Jonas <notifications@github.com> wrote:
 

 @ewamiti something along these lines:Interferogram
s1tbx_InterferogramFormation
Interferogram Formation
Radar
ParameterRaster|sourceProduct|Input image|False|False
ParameterBoolean|subtractFlatEarthPhase|Subtract Flat Earth phase|True
ParameterNumber|srpPolynomialDegree|Degree of Flat Earth polynomial|None|None|5
ParameterNumber|srpNumberPoints|Number of Flat Earth points|1|None|501
ParameterNumber|orbitDegree|Orbit interpolation degree|None|None|3
ParameterBoolean|includeCoherence|Include coherence estimation|True
ParameterBoolean|squarePixel|Square Pixel|True
ParameterNumber|cohWinRg|Coherence Range Window Size|None|None|10
ParameterNumber|cohWinAz|Coherence Azimuth Window Size|None|None|10
OutputRaster|-out|Output Image
So the first lines are some metadata and the rest specifies the parameters following the format mentioned above.You can also look at the other existing description files for comparison.—

**Comment by ewamiti** [comment]
Created a new issue #42

**Comment by j08lue** [comment]
I guess we can close this issue but should consider to put the instructions and examples somewhere in the documentation as a reference for other users.
