### ISSUE TITLE
WOIS Installation (SNAP Issues)

### ISSUE THREAD

**Issue by ewamiti** [DHI-GRAS/processing_gpf#46]
@radosuav @j08lue
I am training a group of participants in WOIS. During the automatic installation all computer did not complete SNAP installtion. This resulted into the following:
1. WOIS workflow for PG06 on water bodies mapping RADAR does not appear in most computers.
2. In those computers that it appeared, the processing was not saving the output.
Kindly help with a solution.

**Comment by radosuav** [comment]
Discussion moved to https://github.com/TIGER-NET/WOIS_installer/issues/27. 

This issue can be closed.

**Comment by j08lue** [comment]
Thanks for reporting this here @ewamiti
