### ISSUE TITLE
Plans to port qgis-processing-gpf to QGIS 3.x

### ISSUE THREAD

**Issue by PedroVenancio** [DHI-GRAS/processing_gpf#49]
Dear @j08lue and @radosuav 

Are there any plans to port qgis-processing-gpf to QGIS 3.x?

I've tested qgis-processing-gpf in QGIS 2.18.28 with SNAP 7.0 and it seems to be still functional, so as QGIS 2.x reached the EOL, it would be great to have this plugin in QGIS 3.x.

Thank you very much! Best regards!

**Comment by radosuav** [comment]
Hi @PedroVenancio, thanks for testing with the latest SNAP and for the feedback! We do have a plan to update the plugin in the first quarter of 2020. The idea is to make it work with QGIS 3.10 which will be the latest LTR at that time.
Cheers

**Comment by PedroVenancio** [comment]
Oh these are really great news @radosuav ! 

I hope to contribute with some more algorithms in 2020!

Thank you very much for your work and happy new year!

**Comment by radosuav** [comment]
Hi @PedroVenancio, there is now a [QGIS 3 branch](https://github.com/DHI-GRAS/qgis-processing-gpf/tree/qgis-3) of this plugin which contains an almost working version. There are still some [issues](https://github.com/DHI-GRAS/qgis-processing-gpf/issues) remaining but I won't have time to work on them for the next couple of weeks.
